### ISSUE TITLE
Issue with highscore pop up

### ISSUE THREAD

**Issue by fay-bug** [imd1005-web-development-winter-2023/group-project-dobytes#8]
# Issue

## Description

Hello, We are trying to implement a leaderboard system but after you play the game and die the popup shows up before the game over screen and we want to come after because it messes with the animation and sprites. It seems like we put it in the right spot but it's still not working :(

## Screenshot
![image](https://user-images.githubusercontent.com/122563391/230798807-62994cf0-d25c-4843-9a8e-c38477c52048.png)

**Comment by neilmispelaar** [comment]
Hi @aura-git 

I’ll have a quick look in a second. 

At a cursory glance, you may need some sort of a timer delay so that any animations and other calculations are given a moment to end before the popUp() function is fired and the prompt is loaded. 

But I’ll have a look in a bit and get back to you.

**Comment by neilmispelaar** [comment]
In your game, after death, try the following:

```js

// … in game function 

// death occurs 

setTimeout(popUp, 1000);

// this will cause a 1000 millisecond delay before the popUp function is fired - it might give enough time for the animations to end before triggering the prompt 

```

setTimeout() docs: https://developer.mozilla.org/en-US/docs/Web/API/setTimeout

**Comment by fay-bug** [comment]
That worked thank you!!
